add_requires("catch2 v3.15.1")

target("test_token")
    set_kind("binary")
    add_packages("catch2")
    add_deps("alexi_shared")
    add_files("test_token.cpp")
    add_tests("kind", { runargs = {"[kind]"} })
    add_tests("kinds", { runargs = {"[kinds]"} })

target("test_match")
    set_kind("binary")
    add_packages("catch2")
    add_deps("alexi_shared")
    add_files("test_match.cpp")
    add_tests("match", { runargs = {"[match]"} })
