target("alexi_shared")
    set_kind("shared")
    add_includedirs("include")
    add_files("*.cppm", "match/*.cppm", "token/*.cppm", "util/*.cppm", { public = true })
    add_rules("utils.symbols.export_all", {export_classes = true})
