target("alexi_match")
    set_kind("static")
    add_deps("alexi_token", "alexi_util")
    add_includedirs("match/include", {public = true})
    add_files("match/*.cpp")

target("alexi_token")
    set_kind("static")
    add_deps("alexi_util")
    add_includedirs("token/include", {public = true})
    add_files("token/*.cpp")

target("alexi_util")
    set_kind("static")
    add_includedirs("util/include", {public = true})
    add_files("util/*.cpp")

target("alexi")
    set_kind("shared")
    add_deps("alexi_match", "alexi_token", "alexi_util")
    add_rules("utils.symbols.export_all", {export_classes = true})
