name: Alexi CI Local
on:
  workflow_dispatch:

env:
  XMAKE_VERSION: "3.0.9"
  XMAKE_ROOT: y

jobs:
  build:
    name: Test Local Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Toolchain
      run: PLATFORM="linux" scripts/ciinstall.sh
    - name: Build
      run: xmake build
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Build Dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake ninja-build
    - name: Install Toolchain
      run: PLATFORM="linux" scripts/ciinstall.sh
    - name: Build
      run: xmake f --testing=y -y && xmake build -j 2 -y
    - name: Run all tests
      run: xmake test
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Toolchain
        run: PLATFORM="linux" scripts/ciinstall.sh
      - name: Prepare Artifacts Directory
        run: mkdir -p release_packages
      - name: Build & Package Linux AArch64
        run: PLATFORM="linux" ARCH=arm64 TOOLCHAIN="@zig" scripts/cibuild.sh
      - name: Build & Package Linux x86_64
        run: PLATFORM="linux" ARCH=x64 TOOLCHAIN="@zig" scripts/cibuild.sh
  build_macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache Homebrew packages
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/Homebrew
          key: ${{ runner.os }}-brew-llvm22
          restore-keys: ${{ runner.os }}-brew-llvm22
      - name: Install Toolchain
        run: PLATFORM="macos" scripts/ciinstall.sh
      - name: Prepare Artifacts Directory
        run: mkdir -p release_packages
      - name: Build & Package macOS arm64
        run: PLATFORM="macosx" ARCH=arm64 scripts/cibuild.sh
      - name: Build & Package macOS x86_64
        run: PLATFORM="macosx" ARCH=x86_64 scripts/cibuild.sh
  build_win64:
    name: Build Windows x64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Toolchain
        run: PLATFORM="linux" TARGET="windows" scripts/ciinstall.sh
      - name: Prepare Artifacts Directory
        run: mkdir -p release_packages
      - name: Build & Package Windows x86_64
        run: PLATFORM="windows" ARCH=x64 TOOLCHAIN="mingw" scripts/cibuild.sh
