name: C/C++ CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
        build-cache: true
    - name: Build
      run: xmake build -y
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
        build-cache: true
    - name: Build xmake build -y
      run: xmake build -y
    - name: Test lexer
      run: xmake test test_lexer/lexer
    - name: Test matcher rules
      run: xmake test test_matcher/matcher
    - name: Test kind collection handling
      run: xmake test test_token/kinds
    - name: Test kind declaration
      run: xmake test test_token/kind
